# Wave -1 Create ServiceAccount for EKS Pod Identity authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skillpulse-sa
  namespace: skillpulse
  annotations:
    argocd.argoproj.io/sync-wave: "-1"