# Wave 0 Create SecretProviderClass to fetch MySQL secrets from AWS Secrets Manager
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: skillpulse-db-secret
  namespace: skillpulse
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider: aws

  secretObjects:
    - secretName: skillpulse-db
      type: Opaque
      data:
        - objectName: MYSQL_ROOT_PASSWORD
          key: MYSQL_ROOT_PASSWORD
        - objectName: MYSQL_DATABASE
          key: MYSQL_DATABASE
        - objectName: MYSQL_USER
          key: MYSQL_USER
        - objectName: MYSQL_PASSWORD
          key: MYSQL_PASSWORD

  parameters:
    objects: |
      - objectName: "skillpulse-db"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MYSQL_ROOT_PASSWORD"
            objectAlias: "MYSQL_ROOT_PASSWORD"
          - path: "MYSQL_DATABASE"
            objectAlias: "MYSQL_DATABASE"
          - path: "MYSQL_USER"
            objectAlias: "MYSQL_USER"
          - path: "MYSQL_PASSWORD"
            objectAlias: "MYSQL_PASSWORD"