# Wave 4 Deploy backend application after MySQL availability
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: skillpulse
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mysql:8.4
          command:
            - sh
            - -c
            - |
              until mysqladmin ping -h mysql --silent; do
                echo "Waiting for MySQL..."
                sleep 2
              done
      containers:
        - name: backend
          image: 324761312512.dkr.ecr.ap-south-1.amazonaws.com/skillpulse-backend:e5040c6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: PORT
              value: "8080"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2