name: CD (Eks cluster — manifest bump)

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

# permissions:
#   id-token: write
#   contents: read

jobs:
  bump-manifests:
    if: ${{ github.event.workflow_run.conclusion == 'success' && vars.DEPLOY_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    env:
      REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pin backend + frontend images to commit SHA
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          set -e

          # convert full SHA → short SHA
          SHA=$(echo "$SHA" | cut -c1-7)

          echo "Updating manifests with image tag: $SHA"

          sed -i "s|image: .*/skillpulse-backend:.*|image: ${REGISTRY}/skillpulse-backend:${SHA}|" k8s/08-backend-deployment.yaml
          sed -i "s|image: .*/skillpulse-frontend:.*|image: ${REGISTRY}/skillpulse-frontend:${SHA}|" k8s/11-frontend-deployment.yaml

      - name: Commit + push if changed
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          set -e

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add k8s/08-backend-deployment.yaml k8s/11-frontend-deployment.yaml

          git commit -m "deploy: pin images to $(echo $SHA | cut -c1-7)"
          git push