name: CD Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline (Security + Build)"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            REPO=~/app

            # Clone if not exists
            if [ ! -d "$REPO" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }}.git $REPO
            fi

            cd $REPO
            git pull origin main
            SHA=$(git rev-parse HEAD)
            IMAGE_TAG=${SHA::7}

            # Docker login
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Clean env
            : > .env

            # Create env safely
            printf "DOCKERHUB_USERNAME=%s\n" "${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            printf "IMAGE_TAG=%s\n" "$IMAGE_TAG" >> .env

            printf "DB_NAME=%s\n" "${{ secrets.DB_NAME }}" >> .env
            printf "DB_USER=%s\n" "${{ secrets.DB_USER }}" >> .env
            printf "DB_PASSWORD=%s\n" "${{ secrets.DB_PASSWORD }}" >> .env
            printf "MYSQL_ROOT_PASSWORD=%s\n" "${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env

            # Deploy
            docker compose pull
            docker compose up -d