name: CI Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "k8s/**"
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:

  secrets:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2

  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile

  go-security:
    name: Go Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
      - name: Checks
        run: |
          cd backend
          go vet ./...
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [secrets, lint, go-security]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Set Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/skillpulse-backend:${{ env.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/skillpulse-backend:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/skillpulse-backend:cache,mode=max

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [secrets, lint, go-security]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Set Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/skillpulse-frontend:${{ env.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/skillpulse-frontend:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/skillpulse-frontend:cache,mode=max

  trivy-backend:
    name: Trivy Backend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/skillpulse-backend:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

  trivy-frontend:
    name: Trivy Frontend
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/skillpulse-frontend:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true